### ISSUE TITLE
texlive-full statt texlive

### ISSUE THREAD

**Issue by Lasse92** [uni-due-syssec/thesis-template#4]
Wenn man 'texlive' intalliert, fehlen viele packages, die von tlmgr (zumindest bei mir) auch nicht im repository gefunden werden können.
Installiert man stattdessen 'texlive-full' müssen anschließend keine gesonderten packages mit tlmgr installiert weden.

**Comment by 0drai** [comment]
Danke für das feedback. Wir wollten die benötigten packages so klein wie möglich halten. 

Um dir das suchen der packages zu ersparen, haben wir ein Dockerfile geschrieben die das compilen erledigen. Damit musst du dir keine Sorgen um die benötigten packages machen. Du kannst es gerne ausprobieren wenn du magst. Die Dockerfiles sind im neusten commit.

Eine kleine Anleitung zur Anwendung der Docker findest du in der README.md file. 

Wenn du Fragen, Anmerkungen oder bugs gefunden hast, bitte melden.
