### ISSUE TITLE
"Titel" unten links auf jeder Seite

### ISSUE THREAD

**Issue by Lasse92** [uni-due-syssec/thesis-template#5]
Mir ist aufgefallen, dass unten links auf jeder Seite in der Ausgabe-PDF immer nur "Titel" steht. Ich glaube hier soll wohl der eigentliche Titel der Arbeit stehen. Dazu habe ich in syssec-report.cls in den Zeilen 36 und 54 (ich weiß nicht genau, welche von beiden ausschlaggebend ist) `\lfoot[\@stringTitle]{\@stringTitle}` in `\lfoot[\@stringTitle]{\@title}` geändert.

**Comment by 0drai** [comment]
Danke. Ist im aktuellen commit gefixed
