### ISSUE TITLE
\section{} erstellt immer eine neue Seite : /

### ISSUE THREAD

**Issue by ghost** [uni-due-syssec/thesis-template#7]
Hi Sam,
es gibt leider das Problem, dass wenn ich \section{} in dem Template verwende automatisch immer eine neue Seite angelegt wird. Ich habe mit Michael Rodler drüber gesprochen, und er meinte, das soll so nicht sein. Besser wäre es auf einer Seite zu belassen.
LG
David

**Comment by 0drai** [comment]
Hi,
danke für den Hinweis. Ist im neusten commit geändert. Du musst in der `syssec-report.cls` Zeile 33 löschen.

lg
