### ISSUE TITLE
Acknowledgement und Eidesstattlicheerklärung

### ISSUE THREAD

**Issue by ghost** [uni-due-syssec/thesis-template#9]
Hi Sam,
beide werde in einem Report nicht gebraucht, aber trotzdem generiert.
LG
David

**Comment by 0drai** [comment]
Die eidesstattliche Erklärung wird beim Report nicht ausgegeben (926cf8bcfddb6c507558e77891bf166217eb78ba). Vielleicht musst du neu pullen. Das Acknowledgement kannst du rausnehmen in dem du die Zeile ```\input{components/acknowledgements.tex}``` aus der main.tex file löschst.

lg
